services:
  mongodb:
    image: "mongo:7.0.12-rc1-jammy"
    container_name: "real-time-lb"
    ports:
      - "27024:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seu
      - MONGO_INITDB_ROOT_PASSWORD=seu
    restart: always
    healthcheck:
      test: echo 'db.runCommand({find:"real-time-lb.seu"}).ok' | mongosh --authenticationDatabase admin --host localhost -u seu -p seu admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - course_mongodb_data_vol:/data/db/
      - course_mongodb_log_vol:/var/log/mongodb/
    networks:
      - course_mongodb_net

volumes:
  course_mongodb_data_vol:
  course_mongodb_log_vol:

networks:
  course_mongodb_net: